Name:		chicken
Version:	4.4.0
Release:	2%{?dist}
Summary:        Scheme-to-C compiler

Group:		Development/Languages 	
License:	BSD
URL:		http://www.call-with-current-continuation.org/chicken-4.4.0.tar.gz

Source0:	chicken-%{version}.tar.gz
Patch0:	chicken-lib64.patch

BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires: chrpath

#BuildRequires:	
#Requires:	

%description
CHICKEN is a Scheme-to-C compiler supporting the language
features as defined in the 'Revised Report on
Scheme'. Separate compilation is supported and full
tail-recursion and efficient first-class continuations are
available.

Some things that CHICKEN has to offer:

1. CHICKEN generates quite portable C code and compiled files
   generated by it (including itself) should work without any
   changes on DOS, Windows, most UNIX-like platforms, and with
   minor changes on other systems.

2. The whole package is distributed under a BSD style license
   and as such is free to use and modify as long as you agree
   to its terms.

3. Linkage to C modules and C library functions is
   straightforward. Compiled programs can easily be embedded
   into existing C code.

4. Loads of extra libraries.



%prep
%setup -q

%ifarch x86_64
%patch0 -p0
%endif


%build

make PLATFORM=linux PREFIX=/usr  LIBDIR=%{_libdir}  #%{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/usr
make PLATFORM=linux PREFIX=/usr LIBDIR=/usr/lib64  DESTDIR=$RPM_BUILD_ROOT install


chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/chicken.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/posix.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/csi.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/setup-download.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/srfi-4.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/lolevel.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/srfi-1.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/foreign.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/extras.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/srfi-13.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/setup-download.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/ports.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/utils.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/setup-api.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/tcp.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/irregex.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/srfi-18.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/scheme.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/files.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/setup-api.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/srfi-14.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/srfi-69.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/regex.import.so 
chrpath --delete $RPM_BUILD_ROOT%{_libdir}/chicken/5/data-structures.import.so 
chrpath --delete $RPM_BUILD_ROOT/usr/bin/csc 
chrpath --delete $RPM_BUILD_ROOT/usr/bin/chicken-status 
chrpath --delete $RPM_BUILD_ROOT/usr/bin/csi 
chrpath --delete $RPM_BUILD_ROOT/usr/bin/chicken-install 
chrpath --delete $RPM_BUILD_ROOT/usr/bin/chicken 
chrpath --delete $RPM_BUILD_ROOT/usr/bin/chicken-uninstall 
chrpath --delete $RPM_BUILD_ROOT/usr/bin/chicken-profile 



%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)

/usr/bin/chicken
/usr/bin/chicken-bug
/usr/bin/chicken-install
/usr/bin/chicken-profile
/usr/bin/chicken-status
/usr/bin/chicken-uninstall
/usr/bin/csc
/usr/bin/csi



%dir %{_libdir}/chicken/5/
%{_libdir}/chicken/5/*

%dir /usr/share/chicken
/usr/share/chicken/setup.defaults

%{_libdir}/libchicken.a
%{_libdir}/libchicken.so
%{_libdir}/libchicken.so.5
%{_libdir}/libuchicken.a
%{_libdir}/libuchicken.so
%{_libdir}/libuchicken.so.5

%doc /usr/share/chicken/doc/
%doc /usr/share/man/man1/chicken-bug.1.gz
%doc /usr/share/man/man1/chicken-install.1.gz
%doc /usr/share/man/man1/chicken-profile.1.gz
%doc /usr/share/man/man1/chicken-status.1.gz
%doc /usr/share/man/man1/chicken-uninstall.1.gz
%doc /usr/share/man/man1/chicken.1.gz
%doc /usr/share/man/man1/csc.1.gz
%doc /usr/share/man/man1/csi.1.gz

#rpmlint thins should be devel packages, but chicken is unusable without them
/usr/include/chicken-config.h
/usr/include/chicken.h

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig


%changelog
* Wed Mar 31 2010 Adam Young <ayoung@redhat.com> - 4.4.0-1
- Initial creation of specfile



